version: '3'
services:
  app:
    container_name: blog
    restart: always
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - blog-app
networks:
  blog-app:
    driver: bridge
