version: '3'
services:
  blog:
    container_name: blog-container
    restart: always
    build: ./
    ports:
      - '80:3000'
    volumes:
      - ./:/usr/src/nextblog
      - /usr/src/nextblog/node_modules
      - /usr/src/nextblog/.next
    networks:
      - blog-app
networks:
  blog-app:
    driver: bridge
