version: '3'
services:
  blog:
    container_name: blog-container
    restart: always
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/blog
      - /usr/src/blog/node_modules
      - /usr/src/blog/.next
    networks:
      - blog-app
networks:
  blog-app:
    driver: bridge
