version: '3'
services:
  blog:
    container_name: blog-container
    restart: always
    build: ./
    env_file: .env.local
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - blog-app
networks:
  blog-app:
    driver: bridge
